### ISSUE TITLE
Peer Review - Kevin Hernandez-Pedroza

### ISSUE THREAD

**Issue by khernandezpedroza** [wilsoncip/travel-journal#1]
Hi Wilson,

Your website is very organized and easy to follow. The colors make it look very professional and approachable. However, I do have some concerns with the header. I feel like you should spread the content tabs onto the right side and keep the home button on the left side. This will help you take over much of the space of the website and not make it look empty. I also noticed that your sitemap link is very small and I didn't notice it at first. I recommend you increase the font size of it so the audience is aware that it is accessible on all the pages of the website. 

Your code is also very organized. It is easy to read but you should add the "p" HTML element in your code so you can represent the text as a paragraph and not just have it as a text floating around. It is also easier to add style to it if you add text as a block of elements. I also noticed your incorrect use of  "divs". Similar to the p block element, you should add the headers as a "h1" block instead of the div. The divs are mainly used to categorize several HTML elements and not just texts. 

Overall your website looks great!

Best,
Kevin Hernandez-Pedroza

**Comment by wilsoncip** [comment]
Thank you so much for your review! Sorry for the late reply but your advice was of great help. Thanks.
