### ISSUE TITLE
Peer Review- Caroline Reilly

### ISSUE THREAD

**Issue by carolinereilly** [wilsoncip/travel-journal#2]
Hi Wilson! 

I loved going through your website and I think you did a great job on it. 

Technical issues:
1.) The "sitemap" on all of the pages are very small and hard to find. Maybe you could change the color, size or font in your code to make it easier to locate and click. People might disregard it so it could be nice to make it more noticeable. 
2.) Similar to the "sitemap", on your homepage, the words "Click here to read more" are also challenging to see and click. Maybe you could also change the size and color in your code to make it easier to read. Again, you want to make it more noticeable so your hard work on that content is seen! 

Suggestions on content:
1.) I think it would be fascinating to see a page where you want to travel next. Maybe you could add this page and talk about your future travel trips and why you would like to go there.
2.) I think it would also be great to add in some videos from these trips. Even a Youtube video talking about Japan, Iceland or Canada could be extremely interesting. All of your pages are set up very similar so it could be nice to add some different elements such as a video on certain pages. 

Again, great job!

Best, 
Caroline Reilly

**Comment by wilsoncip** [comment]
Thank you so much for your review! Sorry for the late reply but your advice was of great help. Thanks.
